name: CI
on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]
jobs:
  build:
    uses: softwaremill/github-actions-workflows/.github/workflows/build-scala.yml@main
    # Run on external PRs, but not on internal PRs since those will be run by push to branch
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    with:
      java-opts: '-Xmx4G'

  publish:
    uses: softwaremill/github-actions-workflows/.github/workflows/publish-release.yml@main
    needs: [build]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    secrets: inherit
    with:
      java-opts: '-Xmx4G'